[package]
name = "binary-brain"
version = "0.4.0"
authors = ["Pjottos <->"]
edition = "2018"


[dependencies]
rand = "0.7"
rayon = "1"
byteorder = "1"

[dev_dependencies]
gym = "2.2"

[profile.bench]
debug = true
